import { Inter } from "next/font/google";
import "./globals.css";
import {Disclosure, Menu, Transition} from "@headlessui/react";
import {Bars3Icon, BellIcon, XMarkIcon} from "@heroicons/react/24/outline";
import {Fragment} from "react";
import Navigation from "@/components/nav/Navigation";
import StripeElementsProvider from "@/components/providers/StripeElementsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
    <head>
        <script
            async
            src="https://js.stripe.com/v3/pricing-table.js">
        </script>
        <script async
                src="https://js.stripe.com/v3/buy-button.js">
        </script>

    </head>
      <body className={inter.className}>
      <StripeElementsProvider>
          <Navigation />

          {children}
      </StripeElementsProvider>


      </body>
    </html>
  );
}
